project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "RBiotools"      
    logo-href: about.qmd    
    left:
      - href: about.qmd
        text: About
        icon: house-fill
      - href: getting_started.qmd
        text: Getting Started
        icon: info

format:
  html:
    theme:
      - lumen
      - brand
    css: styles.css
    toc: true



